# Generated by Django 4.1.3 on 2022-12-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["created"]},
        ),
    ]
